apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-demo-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsprod
   profiles: []
   projectId: tcb-k8s-412616
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/gkemedium/locations/us-central1/clusters/cluster-1